# Generated by Django 5.2.7 on 2025-11-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=50)),
                ('authorName', models.CharField(max_length=50)),
                ('publishedDate', models.CharField(max_length=10)),
                ('ratings', models.IntegerField(default=0)),
                ('price', models.FloatField()),
            ],
        ),
    ]
