# Generated by Django 5.2.7 on 2025-11-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AuthorName', models.CharField(max_length=100)),
                ('AuthorAge', models.IntegerField()),
                ('AuthorPhone', models.CharField(blank=True, max_length=20)),
                ('AuthorEmail', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
